modLoader="javafml"
loaderVersion="[47,)"
logoFile="environs.png"
license="All Rights Reserved"

[[mods]]
    displayName="Environs"    
    version="1.0.1"
    modId="tltemplates"
    credits=""
    authors="burnsqc"
    description=""

[[dependencies.environs]] 
    modId="forge" 
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.environs]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"
